  on: push
  jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses:  actions/setup-java@v3.0.0
          with:
            java-verison: '11'
            distribution: 'adopt'
            cache: maven
        - run:  mvn --batch-mode --update-snapshots verify