  on: push
  jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Set Up JDK 11
          uses:  actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '11'
            cache: maven
        - run:  mvn --batch-mode --update-snapshots verify